// Simplified → Traditional Chinese conversion (replaces external OpenCC dependency).
//
// Pipeline (mirrors OpenCC s2t + TWVariants):
//   1. STPhrases: longest-match phrase substitution via daachorse AC
//   2. STCharacters: single-character HashMap fallback
//   3. TWVariants: Taiwan-specific variant normalization
//
// Dictionary data is pre-generated by scripts/gen-s2t-tables.py into
// s2t_data.rs (static arrays). No runtime text parsing needed.

#[path = "s2t_data.rs"]
mod s2t_data;

use std::collections::HashMap;

use daachorse::{CharwiseDoubleArrayAhoCorasickBuilder, MatchKind as DaacMatchKind};

// Converter

/// Compiled SC→TC converter. Build once, reuse across calls.
pub struct S2TConverter {
    /// Phrase AC automaton (longest-match). Match value = index into `phrase_targets`.
    phrase_ac: daachorse::CharwiseDoubleArrayAhoCorasick<u32>,
    /// Target strings for phrase matches, parallel to AC pattern indices.
    phrase_targets: Vec<&'static str>,
    /// Single-character SC→TC map (fallback after phrase matching).
    char_map: HashMap<char, char>,
    /// TW variant normalization map (applied last).
    tw_variant_map: HashMap<char, char>,
}

impl Default for S2TConverter {
    fn default() -> Self {
        Self::new()
    }
}

impl S2TConverter {
    /// Build the converter from pre-generated static tables.
    ///
    /// Panics if the daachorse AC build fails (should never happen with
    /// well-formed dictionary data).
    pub fn new() -> Self {
        // Build phrase targets vec and AC patterns from static data.
        let mut phrase_targets: Vec<&'static str> = Vec::with_capacity(s2t_data::ST_PHRASES.len());

        let patvals: Vec<(&str, u32)> = s2t_data::ST_PHRASES
            .iter()
            .enumerate()
            .map(|(i, &(key, val))| {
                phrase_targets.push(val);
                (key, i as u32)
            })
            .collect();

        let phrase_ac = CharwiseDoubleArrayAhoCorasickBuilder::new()
            .match_kind(DaacMatchKind::LeftmostLongest)
            .build_with_values(patvals)
            .expect("s2t phrase AC build");

        // Build character maps from static arrays.
        let char_map: HashMap<char, char> = s2t_data::ST_CHARACTERS.iter().copied().collect();
        let tw_variant_map: HashMap<char, char> = s2t_data::TW_VARIANTS.iter().copied().collect();

        Self {
            phrase_ac,
            phrase_targets,
            char_map,
            tw_variant_map,
        }
    }

    /// Convert Simplified Chinese text to Traditional Chinese (Taiwan variant).
    pub fn convert(&self, input: &str) -> String {
        // Scan for phrase matches. Between matches (and after the last match),
        // apply character-level conversion.
        let mut out = String::with_capacity(input.len());
        let mut last_byte = 0;

        for mat in self.phrase_ac.leftmost_find_iter(input) {
            let start = mat.start();
            let end = mat.end();

            // Convert unmatched gap character-by-character.
            for ch in input[last_byte..start].chars() {
                out.push(self.convert_char(ch));
            }

            // Substitute matched phrase.
            let idx = mat.value() as usize;
            out.push_str(self.phrase_targets[idx]);

            last_byte = end;
        }

        // Convert remaining tail.
        for ch in input[last_byte..].chars() {
            out.push(self.convert_char(ch));
        }

        // TW variant normalization.
        if self.tw_variant_map.is_empty() {
            return out;
        }
        let mut result = String::with_capacity(out.len());
        for ch in out.chars() {
            result.push(*self.tw_variant_map.get(&ch).unwrap_or(&ch));
        }
        result
    }

    /// Convert a single character using STCharacters map.
    #[inline]
    fn convert_char(&self, ch: char) -> char {
        *self.char_map.get(&ch).unwrap_or(&ch)
    }

    /// Number of phrase patterns in the AC automaton.
    pub fn phrase_count(&self) -> usize {
        self.phrase_targets.len()
    }

    /// Number of character mappings.
    pub fn char_count(&self) -> usize {
        self.char_map.len()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn converter() -> S2TConverter {
        S2TConverter::new()
    }

    #[test]
    fn basic_character_conversion() {
        let c = converter();
        assert_eq!(c.convert("国"), "國");
        assert_eq!(c.convert("学"), "學");
        assert_eq!(c.convert("计算机"), "計算機");
    }

    #[test]
    fn phrase_conversion() {
        let c = converter();
        // STPhrases handles context-dependent multi-char mappings.
        // Note: 操作系统→操作系統 (char-level only, no TWPhrases).
        // 作業系統 is a TWPhrases mapping that zhtw-mcp handles separately.
        assert_eq!(c.convert("操作系统"), "操作系統");
        // 内存→內存 (char-level only). 記憶體 is a TWPhrases mapping
        // handled by zhtw-mcp's cross_strait rules, not by s2t.
        assert_eq!(c.convert("内存"), "內存");
        // 一丝不挂→一絲不掛 (in STPhrases: phrase-level conversion).
        assert_eq!(c.convert("一丝不挂"), "一絲不掛");
    }

    #[test]
    fn tw_variant_normalization() {
        let c = converter();
        // TWVariants: 裏→裡, 着→著
        assert_eq!(c.convert("裏"), "裡");
        assert_eq!(c.convert("着"), "著");
    }

    #[test]
    fn mixed_text() {
        let c = converter();
        let input = "这是一个简单的测试";
        let output = c.convert(input);
        // Should be fully Traditional.
        assert!(!output.contains('这'));
        assert!(!output.contains('个'));
        assert!(!output.contains('简'));
    }

    #[test]
    fn ascii_passthrough() {
        let c = converter();
        assert_eq!(c.convert("hello world 123"), "hello world 123");
    }

    #[test]
    fn empty_input() {
        let c = converter();
        assert_eq!(c.convert(""), "");
    }

    #[test]
    fn already_traditional() {
        let c = converter();
        // Traditional text should pass through unchanged.
        assert_eq!(c.convert("國學計算機"), "國學計算機");
    }

    #[test]
    fn dict_sizes_reasonable() {
        let c = converter();
        assert!(
            c.phrase_count() > 35000,
            "expected >35K phrases, got {}",
            c.phrase_count()
        );
        assert!(
            c.char_count() > 3000,
            "expected >3K char mappings, got {}",
            c.char_count()
        );
    }

    #[test]
    fn os_terminology() {
        let c = converter();
        // s2t (char-level) should NOT produce the same wrong results as s2twp.
        // 进程 → 進程 (not 程序, which is what s2twp TWPhrases does)
        assert_eq!(c.convert("进程"), "進程");
        // 并行 → 並行 (char-level only, no TWPhrases override)
        assert_eq!(c.convert("并行"), "並行");
    }
}
